Implementation of the calculation of the area of ​​the rhombus in Exercise 1
Loogan/desafios pull request #13
Opened 2024-11-27 02:07 UTC by Loogan

✨ Pull Request Overview 
This PR adds the functionality for calculating the area of ​​a rhombus in Exercise 1 and closes #1.

📌 Why these changes? 
-These changes are necessary to implement the logic for calculating the area of ​​a rhombus based on the diagonals' values ​​provided by the user. The form now includes input fields for the diagonals and performs validation to ensure proper values ​​are entered. This improves the user experience by allowing seamless interaction and calculation within the exercise.

Feel free to provide any additional feedback or suggestions! 🙌

2024-11-27 12:42 UTC, reenatoteixeira requested changes
There are some minor changes to the exercise 1 structure that must be applied.

2024-11-27 12:42 UTC, reenatoteixeira commented on exercices/exercicio-1/index.html
> +      <input type="number" name="" id="d2" placeholder="Diagonal 2">
1. Given that it's a best practice to use labels when working with inputs, we should add a `label` here for each available input.
2. Given that the `name` attributes are not being used, we can remove them to improve code readability.
3. Given that by adding labels, the placeholder becomes redundant, we can either remove or change them.
```html
      <label for="d1">Diagonal 1:</label>
      <input type="number" id="d1">
      
      <label for="d2">Diagonal 2:</label>
      <input type="number" id="d2">
```

2024-11-27 12:45 UTC, reenatoteixeira commented
> ✨ Pull Request Overview
This PR adds the functionality for calculating the area of ​​a rhombus in Exercise 1 and closes #1.
> 
> 📌 Why these changes?
-These changes are necessary to implement the logic for calculating the area of ​​a rhombus based on the diagonals' values ​​provided by the user. The form now includes input fields for the diagonals and performs validation to ensure proper values ​​are entered. This improves the user experience by allowing seamless interaction and calculation within the exercise.
> 
> Feel free to provide any additional feedback or suggestions! 🙌

We're closing the wrong issue (#1) here. Please, update the issue number to the correct issue so we don't accidentally close a different issue.

CC @Loogan

2024-11-27 12:49 UTC, reenatoteixeira commented on exercices/exercicio-1/index.html
> +      <a href="/index.html">⇦ Voltar</a>
This `href` attribute will cause problems when deployed. Don't fix it for now, let's leave as it is so we can open a bug-issue to fix it in the future (just to practice different issues/branches/commits).

2024-11-28 00:49 UTC, Loogan commented on exercices/exercicio-1/index.html
> +      <input type="number" name="" id="d2" placeholder="Diagonal 2">
new commit done the problem, please review again.

2024-11-28 02:17 UTC, merged